// 데모 데이터 - API 키 없을 때 사용
// 실감나는 한국 주식 5개 종목 데이터

export const DEMO_MARKET = {
    kospi: 2847.32,
    kospiChange: +0.87,
    kosdaq: 892.15,
    kosdaqChange: +1.23,
    marketStatus: 'open',
    kospiAbove200: true,
};

export const DEMO_SECTORS = [
    { name: '2차전지', netBuy: 412, change: 3.2, trend: 'up' },
    { name: '반도체', netBuy: 287, change: 1.8, trend: 'up' },
    { name: 'AI/소프트웨어', netBuy: 195, change: 2.1, trend: 'up' },
    { name: '바이오', netBuy: 89, change: 0.5, trend: 'neutral' },
    { name: '자동차', netBuy: -156, change: -1.2, trend: 'down' },
    { name: '건설', netBuy: -203, change: -1.8, trend: 'down' },
    { name: '금융', netBuy: 45, change: 0.3, trend: 'neutral' },
    { name: '철강', netBuy: -78, change: -0.9, trend: 'down' },
];

export const DEMO_QUANT_INDEX = {
    momentum: { label: '모멘텀 팩터', value: 82, status: '강함' },
    value: { label: '밸류 팩터', value: 55, status: '보통' },
    volatility: { label: '변동성 지수', value: 35, status: '낮음 (매수 우호)' },
};

export const DEMO_STOCKS = [
    {
        ticker: '247540',
        name: '에코프로비엠',
        sector: '2차전지',
        price: 147500,
        change: 3.2,
        volume: 3842000,
        volumeRatio: 380,
        marketCap: 12500, // 억
        // 수급
        instNetBuy: 45, // 억
        foreignNetBuy: 28,
        retailNetBuy: -73,
        instConsecutiveDays: 4,
        foreignConsecutiveDays: 6,
        instAlwaysBuy: true,
        instMultipleBuyers: true,
        creditRatio: 1.2,
        lendingIncrease: 3,
        recentDrop: -2,
        volumeEarlyBreak: true,
        // 트레이더 기법
        ma50: 142000, ma150: 135000, ma200: 128000,
        ma200Trend: 'up',
        week52Low: 98000, week52High: 155000,
        vcpContraction: true, vcpVolumeBreak: true,
        quarterlyEarningsGrowth: 35,
        annualEarningsYears: 3,
        isNewHigh: false,
        sharesOutstanding: 32000000,
        sectorRank: 12,
        instNewBuyers: 5,
        kospiAbove200: true,
        breakoutResistance: true, breakoutVolume: 250,
        closedAboveResistance: true, trendDirection: 'up',
        stage: 2, ma30wSlope: 'strong_up', volumeAboveAvg: true,
        darvasBoxClear: true, darvasBreakout: true, darvasSupport: true,
        returns1m: 8, returns3m: 22, returns6m: 45, returns12m: 78,
        pbr: 1.2, roe: 18, debtRatio: 65, operatingMargin: 12,
        nearHigh52: true, volumeSurge: true,
        // 퀀트
        momentumRank: 8,
        roeRank: 15, operatingMarginRank: 18, debtRatioRank: 78,
        pbrRank: 55, perRank: 62, psrRank: 58,
        volatilityRank: 45, beta: 1.1,
        targetPriceRevisionUp: true, earningSurprise: true,
        orderBook: { totalBid: 85000, totalAsk: 42000, bidRatio: 67, bidDominant: true, askDisappearing: false },
        derivatives: { instFuturesBuy: true, instFuturesAmount: 320, callDominant: true, putCallRatio: 0.72, callOIIncreasing: true },
    },
    {
        ticker: '000660',
        name: 'SK하이닉스',
        sector: '반도체',
        price: 178000,
        change: 2.8,
        volume: 5120000,
        volumeRatio: 290,
        marketCap: 125000,
        instNetBuy: 82,
        foreignNetBuy: 55,
        retailNetBuy: -137,
        instConsecutiveDays: 5,
        foreignConsecutiveDays: 8,
        instAlwaysBuy: true,
        instMultipleBuyers: true,
        creditRatio: 0.5,
        lendingIncrease: 2,
        recentDrop: 0,
        volumeEarlyBreak: true,
        ma50: 170000, ma150: 162000, ma200: 155000,
        ma200Trend: 'up',
        week52Low: 105000, week52High: 185000,
        vcpContraction: true, vcpVolumeBreak: true,
        quarterlyEarningsGrowth: 120,
        annualEarningsYears: 2,
        isNewHigh: false,
        sharesOutstanding: 728000000,
        sectorRank: 5,
        instNewBuyers: 8,
        kospiAbove200: true,
        breakoutResistance: true, breakoutVolume: 220,
        closedAboveResistance: true, trendDirection: 'up',
        stage: 2, ma30wSlope: 'strong_up', volumeAboveAvg: true,
        darvasBoxClear: true, darvasBreakout: true, darvasSupport: false,
        returns1m: 5, returns3m: 18, returns6m: 38, returns12m: 65,
        pbr: 1.8, roe: 22, debtRatio: 45, operatingMargin: 28,
        nearHigh52: true, volumeSurge: true,
        momentumRank: 12,
        roeRank: 8, operatingMarginRank: 5, debtRatioRank: 82,
        pbrRank: 42, perRank: 48, psrRank: 45,
        volatilityRank: 38, beta: 1.15,
        targetPriceRevisionUp: true, earningSurprise: true,
        orderBook: { totalBid: 120000, totalAsk: 55000, bidRatio: 69, bidDominant: true, askDisappearing: false },
        derivatives: { instFuturesBuy: true, instFuturesAmount: 320, callDominant: true, putCallRatio: 0.72, callOIIncreasing: true },
    },
    {
        ticker: '035720',
        name: '카카오',
        sector: 'AI/소프트웨어',
        price: 58900,
        change: 4.1,
        volume: 8950000,
        volumeRatio: 420,
        marketCap: 26200,
        instNetBuy: 38,
        foreignNetBuy: 22,
        retailNetBuy: -60,
        instConsecutiveDays: 3,
        foreignConsecutiveDays: 4,
        instAlwaysBuy: false,
        instMultipleBuyers: true,
        creditRatio: 1.8,
        lendingIncrease: 5,
        recentDrop: -1,
        volumeEarlyBreak: false,
        ma50: 55000, ma150: 52000, ma200: 49000,
        ma200Trend: 'up',
        week52Low: 38000, week52High: 62000,
        vcpContraction: true, vcpVolumeBreak: false,
        quarterlyEarningsGrowth: 28,
        annualEarningsYears: 2,
        isNewHigh: false,
        sharesOutstanding: 445000000,
        sectorRank: 15,
        instNewBuyers: 4,
        kospiAbove200: true,
        breakoutResistance: false, breakoutVolume: 180,
        closedAboveResistance: false, trendDirection: 'up',
        stage: 2, ma30wSlope: 'up', volumeAboveAvg: true,
        darvasBoxClear: true, darvasBreakout: false, darvasSupport: true,
        returns1m: 12, returns3m: 15, returns6m: 28, returns12m: 42,
        pbr: 1.4, roe: 12, debtRatio: 55, operatingMargin: 15,
        nearHigh52: false, volumeSurge: true,
        momentumRank: 15,
        roeRank: 22, operatingMarginRank: 20, debtRatioRank: 75,
        pbrRank: 58, perRank: 55, psrRank: 52,
        volatilityRank: 52, beta: 0.95,
        targetPriceRevisionUp: true, earningSurprise: false,
        orderBook: { totalBid: 65000, totalAsk: 58000, bidRatio: 53, bidDominant: false, askDisappearing: false },
        derivatives: { instFuturesBuy: true, instFuturesAmount: 320, callDominant: true, putCallRatio: 0.72, callOIIncreasing: true },
    },
    {
        ticker: '068270',
        name: '셀트리온',
        sector: '바이오',
        price: 192300,
        change: 1.5,
        volume: 1250000,
        volumeRatio: 210,
        marketCap: 42800,
        instNetBuy: 25,
        foreignNetBuy: 12,
        retailNetBuy: -37,
        instConsecutiveDays: 2,
        foreignConsecutiveDays: 3,
        instAlwaysBuy: false,
        instMultipleBuyers: false,
        creditRatio: 0.8,
        lendingIncrease: 1,
        recentDrop: 0,
        volumeEarlyBreak: false,
        ma50: 187000, ma150: 180000, ma200: 175000,
        ma200Trend: 'up',
        week52Low: 152000, week52High: 198000,
        vcpContraction: false, vcpVolumeBreak: false,
        quarterlyEarningsGrowth: 45,
        annualEarningsYears: 4,
        isNewHigh: false,
        sharesOutstanding: 138000000,
        sectorRank: 10,
        instNewBuyers: 3,
        kospiAbove200: true,
        breakoutResistance: false, breakoutVolume: 150,
        closedAboveResistance: false, trendDirection: 'up',
        stage: 2, ma30wSlope: 'up', volumeAboveAvg: true,
        darvasBoxClear: true, darvasBreakout: false, darvasSupport: true,
        returns1m: 3, returns3m: 12, returns6m: 18, returns12m: 25,
        pbr: 2.8, roe: 15, debtRatio: 35, operatingMargin: 22,
        nearHigh52: true, volumeSurge: false,
        momentumRank: 25,
        roeRank: 20, operatingMarginRank: 12, debtRatioRank: 88,
        pbrRank: 35, perRank: 40, psrRank: 42,
        volatilityRank: 68, beta: 0.72,
        targetPriceRevisionUp: true, earningSurprise: true,
        orderBook: { totalBid: 48000, totalAsk: 52000, bidRatio: 48, bidDominant: false, askDisappearing: false },
        derivatives: { instFuturesBuy: true, instFuturesAmount: 320, callDominant: true, putCallRatio: 0.72, callOIIncreasing: true },
    },
    {
        ticker: '005930',
        name: '삼성전자',
        sector: '반도체',
        price: 72800,
        change: 1.2,
        volume: 15800000,
        volumeRatio: 180,
        marketCap: 435000,
        instNetBuy: 120,
        foreignNetBuy: 85,
        retailNetBuy: -205,
        instConsecutiveDays: 6,
        foreignConsecutiveDays: 10,
        instAlwaysBuy: true,
        instMultipleBuyers: true,
        creditRatio: 0.3,
        lendingIncrease: 0,
        recentDrop: 0,
        volumeEarlyBreak: false,
        ma50: 71000, ma150: 69000, ma200: 67000,
        ma200Trend: 'up',
        week52Low: 58000, week52High: 76000,
        vcpContraction: false, vcpVolumeBreak: false,
        quarterlyEarningsGrowth: 55,
        annualEarningsYears: 2,
        isNewHigh: false,
        sharesOutstanding: 5969782550,
        sectorRank: 8,
        instNewBuyers: 12,
        kospiAbove200: true,
        breakoutResistance: false, breakoutVolume: 120,
        closedAboveResistance: false, trendDirection: 'up',
        stage: 2, ma30wSlope: 'up', volumeAboveAvg: false,
        darvasBoxClear: false, darvasBreakout: false, darvasSupport: false,
        returns1m: 4, returns3m: 8, returns6m: 15, returns12m: 22,
        pbr: 1.1, roe: 12, debtRatio: 28, operatingMargin: 18,
        nearHigh52: true, volumeSurge: false,
        momentumRank: 30,
        roeRank: 25, operatingMarginRank: 22, debtRatioRank: 90,
        pbrRank: 65, perRank: 58, psrRank: 55,
        volatilityRank: 72, beta: 0.85,
        targetPriceRevisionUp: true, earningSurprise: false,
        orderBook: { totalBid: 280000, totalAsk: 95000, bidRatio: 75, bidDominant: true, askDisappearing: true },
        derivatives: { instFuturesBuy: true, instFuturesAmount: 320, callDominant: true, putCallRatio: 0.72, callOIIncreasing: true },
    },
];

// AI 분석 데모 텍스트
export const DEMO_ANALYSIS = {
    '247540': '기관과 외국인이 동시에 대량 매수하는 쌍끌이 패턴으로, 4일 연속 순매수가 누적되며 강한 수급 지지를 보이고 있습니다. 미너비니 VCP 수렴 후 거래량 380% 폭발과 함께 돌파 신호가 발생했으며, 와인스타인 Stage 2 강한 상승 추세가 확인됩니다. 모멘텀·퀄리티·밸류·이익개선 4개 퀀트 팩터 동시 충족으로 역대 유사 패턴 평균 수익률 +8.3%, 승률 71%에 해당합니다. 147,500원 진입 후 156,400원(+6%)에서 절반 익절, 140,100원 이탈 시 전량 손절을 권고하며, 이는 투자 권유가 아닌 분석 정보입니다.',
    '000660': '기관 82억·외국인 55억 동시 순매수의 강력한 쌍끌이 수급이 8일째 지속되며, HBM 수요 확대 수혜 기대감이 가격에 반영되고 있습니다. 50일>150일>200일 완전 정배열 속 52주 고점 돌파를 시도 중이며, 와인스타인 Stage 2 강한 상승 구간에 위치합니다. ROE 22%, 영업이익률 28%의 퀄리티와 분기 이익 120% 성장이 어닝 서프라이즈와 함께 퀀트 팩터를 충족합니다. 178,000원 매수 후 188,600원(+6%)에서 1차 익절, 169,100원 이탈 시 손절하며, 이는 투자 권유가 아닌 분석 정보입니다.',
    '035720': '기관 38억·외국인 22억 동시 순매수로 4거래일 연속 수급이 유입되며, AI 사업 확장 기대감이 주가를 견인하고 있습니다. 200일선 우상향 속 VCP 수렴 패턴이 형성 중이며, 62,000원 저항선 돌파 시 추가 상승 모멘텀이 기대됩니다. PBR 1.4배에 ROE 12%, 모멘텀 상위 15%로 가치와 성장이 균형 잡힌 종목입니다. 58,900원 진입 후 62,400원(+6%)에서 1차 익절, 55,500원 이탈 시 손절하며, 이는 투자 권유가 아닌 분석 정보입니다.',
    '068270': '기관·외국인 동시 순매수가 유입되며 바이오 대장주로서 안정적인 수급 흐름을 유지하고 있습니다. 완전 정배열 상태에서 198,000원 52주 최고가 돌파를 시도 중이며, Stage 2 상승 추세가 명확합니다. 연간 영업이익 4년 연속 증가에 어닝 서프라이즈까지 기록하며 퀄리티 팩터가 돋보입니다. 192,300원 진입 후 203,800원(+6%)에서 1차 익절, 182,700원 이탈 시 손절하며, 이는 투자 권유가 아닌 분석 정보입니다.',
    '005930': '기관 120억·외국인 85억의 압도적 쌍끌이 수급이 6거래일 연속 유입되며, 시장 전체 자금이 반도체로 집중되고 있습니다. 200일선 우상향 속 Stage 2 상승 추세가 유지되고 있으나, VCP 수렴이나 피벗 돌파 패턴은 아직 미완성입니다. PBR 1.1배의 저평가 영역에서 부채비율 28%, 영업이익률 18%의 견고한 퀄리티를 보이고 있습니다. 72,800원 진입 후 76,400원(+5%)에서 1차 익절, 69,200원 이탈 시 손절하며, 이는 투자 권유가 아닌 분석 정보입니다.',
};
